#!/bin/bash
# prvni projekt do ios 
# vytvoril: Jakub Lukas aka xlukas18

COMMAND=""
DATEB="9999-99-99"
DATEA="2020-03-01"
GENDER=""
WIDTH=0
COMMLIST=(infected merege gender age daily monthly yearly countries districts regions)
FILES=""
FILES_GZ=""

printh()
{
	echo "Usage: corona [FILTER] [COMMAND] [LOG [LOG]...]"
	echo ""
	echo "filters:"
	echo "	-a, --after	-a [YYYY-MM-DD]		filters only dates after enterd date"
	echo "	-b, --befhore	-b [YYYY-MM-DD]		filters only dates before entered date"
	echo "	-g, --gender	-G [GENDER]		filters only -- of specific gender"
	echo "commands:"
	echo "	infected,	prints number of all infected from LOG"
	echo "	merege, 	alignes all LOGs into one file"
	echo "	gender		prints number of infected of speific gender Z|M"
	echo "	age, 		prints number of infected of specific age group"
	echo "	daily		prints number of infected for each day"
	echo "	monthly		prints number of infected for each month"
	echo "	yearly		prints number of infected for each year"
	echo "	countries	prints number of infected for every country listed"
	echo "	districts	prints number of infected for every district listed"
	echo "	regions		prints number of infected for each region listed"
	echo ""
	echo "LOGs can be only in .cvs format"
}

while [ "$#" -gt 0 ]; do
	case "$1" in
		${COMMLIST})
			COMMAND=$1
			shift
			;;
		-h)
			printh
			exit
			;;
		-a)
			DATEA=$2
			shift
			shift
			;;
		-b)
			DATEB=$2
			shift
			shift
			;;
		-g)
			GENDER=$2
			shift
			shift
			;;
		-s)
			WIDTH=$2
			shift
			shift
			;;
		*)
			FILES="$1 $FILES"

		esac
done

echo "command: "$COMMAND
echo "date after: "$DATEA
echo "date before: "$DATEB
